version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    container_name: blog_database
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      APP_DB: "${APP_DB}"
      APP_DB_USER: "${APP_DB_USER}"
      APP_DB_PASSWORD: "${APP_DB_PASSWORD}"
      TEST_DB: "${TEST_DB}"
      TEST_DB_USER: "${TEST_DB_USER}"
      TEST_DB_PASSWORD: "${TEST_DB_PASSWORD}"
    ports:
      - "5432:5432"
