version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${APP_DB}"
      POSTGRES_USER: "${APP_DB_USER}"
      POSTGRES_PASSWORD: "${APP_DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  test:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${TEST_DB}"
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASSWORD}"
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"
