#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_DB_USER;
	CREATE DATABASE $APP_DB;
	GRANT CONNECT ON DATABASE $APP_DB TO $APP_DB_USER;
	GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_DB_USER;
    ALTER USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    CREATE USER $TEST_DB_USER;
	CREATE DATABASE $TEST_DB;
	GRANT ALL PRIVILEGES ON DATABASE $TEST_DB TO $TEST_DB_USER;
    ALTER USER $TEST_DB_USER WITH PASSWORD '$TEST_DB_PASSWORD';
EOSQL
